version: '3.3'

services:
  mongodb:
    image: mongo:5.0
    container_name: calilegua-mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '${MONGO_INITDB_PORT}:27017'
    volumes:
      - ./mongo_data:/data/db
